// DaisyUI Theme Service - Maps DaisyUI themes to color values for Remotion scenes
// Follows DESIGN.md: No gradients, solid colors only, DaisyUI palette exclusively

export interface DaisyUITheme {
  name: string;
  colors: {
    primary: string;
    primaryContent: string;
    secondary: string;
    secondaryContent: string;
    accent: string;
    accentContent: string;
    neutral: string;
    neutralContent: string;
    base100: string;
    base200: string;
    base300: string;
    baseContent: string;
    info: string;
    success: string;
    warning: string;
    error: string;
  };
}

// DaisyUI theme color mappings
// Source: https://daisyui.com/docs/themes/
export const daisyUIThemes: Record<string, DaisyUITheme> = {
  light: {
    name: 'light',
    colors: {
      primary: '#570DF8',
      primaryContent: '#FFFFFF',
      secondary: '#F000B8',
      secondaryContent: '#FFFFFF',
      accent: '#37CDBE',
      accentContent: '#FFFFFF',
      neutral: '#3D4451',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F2F2F2',
      base300: '#E5E6E6',
      baseContent: '#1F2937',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  dark: {
    name: 'dark',
    colors: {
      primary: '#661AE6',
      primaryContent: '#FFFFFF',
      secondary: '#D926AA',
      secondaryContent: '#FFFFFF',
      accent: '#1FB2A5',
      accentContent: '#FFFFFF',
      neutral: '#191D24',
      neutralContent: '#A6ADBB',
      base100: '#2A303C',
      base200: '#242933',
      base300: '#20252E',
      baseContent: '#A6ADBB',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  cupcake: {
    name: 'cupcake',
    colors: {
      primary: '#65C3C8',
      primaryContent: '#FFFFFF',
      secondary: '#EF9FBC',
      secondaryContent: '#FFFFFF',
      accent: '#EEAF3A',
      accentContent: '#FFFFFF',
      neutral: '#291334',
      neutralContent: '#FFFFFF',
      base100: '#FAF7F5',
      base200: '#EFEAE6',
      base300: '#E7E2DF',
      baseContent: '#291334',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  bumblebee: {
    name: 'bumblebee',
    colors: {
      primary: '#F9D72F',
      primaryContent: '#181830',
      secondary: '#DF7E07',
      secondaryContent: '#FFFFFF',
      accent: '#181830',
      accentContent: '#FFFFFF',
      neutral: '#181830',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#181830',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  emerald: {
    name: 'emerald',
    colors: {
      primary: '#66CC8A',
      primaryContent: '#FFFFFF',
      secondary: '#377CFB',
      secondaryContent: '#FFFFFF',
      accent: '#EA5234',
      accentContent: '#FFFFFF',
      neutral: '#333C4D',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#333C4D',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  corporate: {
    name: 'corporate',
    colors: {
      primary: '#4B6BFB',
      primaryContent: '#FFFFFF',
      secondary: '#7B92B2',
      secondaryContent: '#FFFFFF',
      accent: '#67CBA0',
      accentContent: '#FFFFFF',
      neutral: '#181A2A',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#181A2A',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  synthwave: {
    name: 'synthwave',
    colors: {
      primary: '#E779C1',
      primaryContent: '#FFFFFF',
      secondary: '#58C7F3',
      secondaryContent: '#FFFFFF',
      accent: '#F9E859',
      accentContent: '#1A103D',
      neutral: '#221551',
      neutralContent: '#FFFFFF',
      base100: '#1A103D',
      base200: '#160D33',
      base300: '#140B2E',
      baseContent: '#FFFFFF',
      info: '#53C0F3',
      success: '#71EAD2',
      warning: '#F3CC30',
      error: '#E24056',
    },
  },
  retro: {
    name: 'retro',
    colors: {
      primary: '#EF9995',
      primaryContent: '#282425',
      secondary: '#A4CDC6',
      secondaryContent: '#282425',
      accent: '#EBD8B2',
      accentContent: '#282425',
      neutral: '#2E282A',
      neutralContent: '#EDE6D4',
      base100: '#E4D8B4',
      base200: '#D2C59D',
      base300: '#C6B386',
      baseContent: '#282425',
      info: '#2563EB',
      success: '#16A34A',
      warning: '#D97706',
      error: '#DC2626',
    },
  },
  cyberpunk: {
    name: 'cyberpunk',
    colors: {
      primary: '#FF7598',
      primaryContent: '#FFFFFF',
      secondary: '#75D1F0',
      secondaryContent: '#FFFFFF',
      accent: '#FFFF00',
      accentContent: '#1A103D',
      neutral: '#221551',
      neutralContent: '#FFFFFF',
      base100: '#FFFF00',
      base200: '#F3F300',
      base300: '#E6E600',
      baseContent: '#1A103D',
      info: '#53C0F3',
      success: '#71EAD2',
      warning: '#F3CC30',
      error: '#E24056',
    },
  },
  valentine: {
    name: 'valentine',
    colors: {
      primary: '#E96D7B',
      primaryContent: '#FFFFFF',
      secondary: '#A991F7',
      secondaryContent: '#FFFFFF',
      accent: '#88DBDD',
      accentContent: '#FFFFFF',
      neutral: '#AF4670',
      neutralContent: '#FFFFFF',
      base100: '#F0D6E8',
      base200: '#E9C4DC',
      base300: '#E1B1CF',
      baseContent: '#632C3B',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  halloween: {
    name: 'halloween',
    colors: {
      primary: '#F28C18',
      primaryContent: '#FFFFFF',
      secondary: '#6D3A9C',
      secondaryContent: '#FFFFFF',
      accent: '#51A800',
      accentContent: '#FFFFFF',
      neutral: '#1B1D1D',
      neutralContent: '#FFFFFF',
      base100: '#212121',
      base200: '#1C1C1C',
      base300: '#171717',
      baseContent: '#FFFFFF',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  garden: {
    name: 'garden',
    colors: {
      primary: '#5C7F67',
      primaryContent: '#FFFFFF',
      secondary: '#ECBCB3',
      secondaryContent: '#FFFFFF',
      accent: '#D5ECC2',
      accentContent: '#1F2937',
      neutral: '#5D5656',
      neutralContent: '#FFFFFF',
      base100: '#E3F2E7',
      base200: '#D1E5D7',
      base300: '#BFD8C7',
      baseContent: '#1F2937',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  forest: {
    name: 'forest',
    colors: {
      primary: '#1EB854',
      primaryContent: '#FFFFFF',
      secondary: '#1DB88E',
      secondaryContent: '#FFFFFF',
      accent: '#1DB8AB',
      accentContent: '#FFFFFF',
      neutral: '#19362D',
      neutralContent: '#FFFFFF',
      base100: '#171212',
      base200: '#110F0F',
      base300: '#0D0C0C',
      baseContent: '#FFFFFF',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  aqua: {
    name: 'aqua',
    colors: {
      primary: '#09ECEC',
      primaryContent: '#005355',
      secondary: '#966FB3',
      secondaryContent: '#FFFFFF',
      accent: '#FFE999',
      accentContent: '#005355',
      neutral: '#3B8AC4',
      neutralContent: '#FFFFFF',
      base100: '#345DA7',
      base200: '#2F5497',
      base300: '#2A4A87',
      baseContent: '#FFFFFF',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  lofi: {
    name: 'lofi',
    colors: {
      primary: '#0D0D0D',
      primaryContent: '#FFFFFF',
      secondary: '#1A1919',
      secondaryContent: '#FFFFFF',
      accent: '#262626',
      accentContent: '#FFFFFF',
      neutral: '#000000',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F2F2F2',
      base300: '#E6E5E5',
      baseContent: '#000000',
      info: '#0070F3',
      success: '#21CC51',
      warning: '#FF6154',
      error: '#DE1C8D',
    },
  },
  pastel: {
    name: 'pastel',
    colors: {
      primary: '#D1C1D7',
      primaryContent: '#1F2937',
      secondary: '#F6CBD1',
      secondaryContent: '#1F2937',
      accent: '#B4E9D6',
      accentContent: '#1F2937',
      neutral: '#70ACC7',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#1F2937',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  fantasy: {
    name: 'fantasy',
    colors: {
      primary: '#6E0B75',
      primaryContent: '#FFFFFF',
      secondary: '#007EDB',
      secondaryContent: '#FFFFFF',
      accent: '#00C7B5',
      accentContent: '#FFFFFF',
      neutral: '#1F2028',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#1F2028',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  wireframe: {
    name: 'wireframe',
    colors: {
      primary: '#B8B8B8',
      primaryContent: '#000000',
      secondary: '#B8B8B8',
      secondaryContent: '#000000',
      accent: '#B8B8B8',
      accentContent: '#000000',
      neutral: '#B8B8B8',
      neutralContent: '#000000',
      base100: '#FFFFFF',
      base200: '#EEEEEE',
      base300: '#DDDDDD',
      baseContent: '#000000',
      info: '#B8B8B8',
      success: '#B8B8B8',
      warning: '#B8B8B8',
      error: '#B8B8B8',
    },
  },
  black: {
    name: 'black',
    colors: {
      primary: '#373737',
      primaryContent: '#FFFFFF',
      secondary: '#373737',
      secondaryContent: '#FFFFFF',
      accent: '#373737',
      accentContent: '#FFFFFF',
      neutral: '#000000',
      neutralContent: '#FFFFFF',
      base100: '#000000',
      base200: '#0D0D0D',
      base300: '#1A1A1A',
      baseContent: '#FFFFFF',
      info: '#0000FF',
      success: '#008000',
      warning: '#FFFF00',
      error: '#FF0000',
    },
  },
  luxury: {
    name: 'luxury',
    colors: {
      primary: '#FFFFFF',
      primaryContent: '#000000',
      secondary: '#152747',
      secondaryContent: '#FFFFFF',
      accent: '#513448',
      accentContent: '#FFFFFF',
      neutral: '#331800',
      neutralContent: '#FFFFFF',
      base100: '#09090B',
      base200: '#0A0A0C',
      base300: '#16151D',
      baseContent: '#FFFFFF',
      info: '#66C7FF',
      success: '#87CF3A',
      warning: '#E1D460',
      error: '#FF6B80',
    },
  },
  dracula: {
    name: 'dracula',
    colors: {
      primary: '#FF79C6',
      primaryContent: '#FFFFFF',
      secondary: '#BD93F9',
      secondaryContent: '#FFFFFF',
      accent: '#FFFF80',
      accentContent: '#1F2937',
      neutral: '#414558',
      neutralContent: '#FFFFFF',
      base100: '#282A36',
      base200: '#1E1F29',
      base300: '#14151C',
      baseContent: '#F8F8F2',
      info: '#8BE9FD',
      success: '#50FA7B',
      warning: '#F1FA8C',
      error: '#FF5555',
    },
  },
  cmyk: {
    name: 'cmyk',
    colors: {
      primary: '#45AEEE',
      primaryContent: '#FFFFFF',
      secondary: '#E8488A',
      secondaryContent: '#FFFFFF',
      accent: '#FFF232',
      accentContent: '#1F2937',
      neutral: '#1A1A1A',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#1A1A1A',
      info: '#4AA8C0',
      success: '#823290',
      warning: '#EE8133',
      error: '#E93F33',
    },
  },
  autumn: {
    name: 'autumn',
    colors: {
      primary: '#8C0327',
      primaryContent: '#FFFFFF',
      secondary: '#D85251',
      secondaryContent: '#FFFFFF',
      accent: '#D59B6A',
      accentContent: '#FFFFFF',
      neutral: '#826A5C',
      neutralContent: '#FFFFFF',
      base100: '#F1F1F1',
      base200: '#E4E4E4',
      base300: '#D7D7D7',
      baseContent: '#1F2937',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  business: {
    name: 'business',
    colors: {
      primary: '#1C4E80',
      primaryContent: '#FFFFFF',
      secondary: '#7C909A',
      secondaryContent: '#FFFFFF',
      accent: '#EA6947',
      accentContent: '#FFFFFF',
      neutral: '#23282E',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F2F7FF',
      base300: '#E5E6E6',
      baseContent: '#23282E',
      info: '#0CA6E9',
      success: '#2BD4BD',
      warning: '#F4C152',
      error: '#FB6F84',
    },
  },
  acid: {
    name: 'acid',
    colors: {
      primary: '#FF00F4',
      primaryContent: '#FFFFFF',
      secondary: '#FF7400',
      secondaryContent: '#FFFFFF',
      accent: '#FFED00',
      accentContent: '#1F2937',
      neutral: '#191A3E',
      neutralContent: '#FFFFFF',
      base100: '#FAFAFA',
      base200: '#EEEEEE',
      base300: '#DDDDDD',
      baseContent: '#191A3E',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  lemonade: {
    name: 'lemonade',
    colors: {
      primary: '#519903',
      primaryContent: '#FFFFFF',
      secondary: '#E9E92E',
      secondaryContent: '#1F2937',
      accent: '#F9F9F9',
      accentContent: '#1F2937',
      neutral: '#191A3E',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F9FAFB',
      base300: '#D1D5DB',
      baseContent: '#191A3E',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  night: {
    name: 'night',
    colors: {
      primary: '#38BDF8',
      primaryContent: '#FFFFFF',
      secondary: '#818CF8',
      secondaryContent: '#FFFFFF',
      accent: '#F471B5',
      accentContent: '#FFFFFF',
      neutral: '#1E293B',
      neutralContent: '#FFFFFF',
      base100: '#0F172A',
      base200: '#1E293B',
      base300: '#334155',
      baseContent: '#CBD5E1',
      info: '#0CA5E9',
      success: '#2DD4BF',
      warning: '#F4BF50',
      error: '#FB7085',
    },
  },
  coffee: {
    name: 'coffee',
    colors: {
      primary: '#DB924B',
      primaryContent: '#FFFFFF',
      secondary: '#6F4C3E',
      secondaryContent: '#FFFFFF',
      accent: '#263E3F',
      accentContent: '#FFFFFF',
      neutral: '#20161F',
      neutralContent: '#FFFFFF',
      base100: '#120C0C',
      base200: '#1C1917',
      base300: '#292524',
      baseContent: '#E7E5E4',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
  winter: {
    name: 'winter',
    colors: {
      primary: '#047AFF',
      primaryContent: '#FFFFFF',
      secondary: '#463AA2',
      secondaryContent: '#FFFFFF',
      accent: '#C148AC',
      accentContent: '#FFFFFF',
      neutral: '#304D6D',
      neutralContent: '#FFFFFF',
      base100: '#FFFFFF',
      base200: '#F2F7FF',
      base300: '#E5E6E6',
      baseContent: '#394E6A',
      info: '#3ABFF8',
      success: '#36D399',
      warning: '#FBBD23',
      error: '#F87272',
    },
  },
};

// Get theme by name
export function getTheme(themeName: string): DaisyUITheme {
  return daisyUIThemes[themeName] || daisyUIThemes.light;
}

// Get all available theme names
export function getAvailableThemes(): string[] {
  return Object.keys(daisyUIThemes);
}

// Convert theme to legacy color scheme format (for backward compatibility)
export function themeToColorScheme(theme: DaisyUITheme) {
  return {
    primary: theme.colors.primary,
    secondary: theme.colors.secondary,
    accent: theme.colors.accent,
    text: theme.colors.baseContent,
    textLight: theme.colors.neutralContent,
    textMuted: theme.colors.base300,
    background: theme.colors.base100,
    borderRadius: 16,
    fontFamily: 'system-ui, -apple-system, sans-serif', // Follow DESIGN.md: use system fonts
  };
}
